name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: savedfeast_test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo, phar, tokenizer, xml, zip
        coverage: xdebug

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL
      run: |
        while ! mysql -h mysql -u root -ppassword -e "SELECT 1" >/dev/null 2>&1; do
          echo "Waiting for MySQL to be ready..."
          sleep 2
        done

    - name: Create Database
      run: |
        mysql -h mysql -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS savedfeast_test;"
        mysql -h mysql -u root -ppassword -e "GRANT ALL PRIVILEGES ON savedfeast_test.* TO 'root'@'%';"
        mysql -h mysql -u root -ppassword -e "FLUSH PRIVILEGES;"

    - name: Run Migrations
      env:
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: savedfeast_test
        DB_USERNAME: root
        DB_PASSWORD: password
        APP_ENV: testing
      run: php artisan migrate --force

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: savedfeast_test
        DB_USERNAME: root
        DB_PASSWORD: password
        APP_ENV: testing
      run: vendor/bin/phpunit

    - name: Run Laravel Pint
      run: vendor/bin/pint --test

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run Security Check
      run: composer audit --format=json --no-interaction
